app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_path:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

