app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api

routing_rest:
    resource: routing_rest.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_path:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user


register:
    path: /pacman/register
    controller: AppBundle\Controller\AuthController::register