<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hqxsf9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hqxsf9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9hqxsf9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9hqxsf9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9hqxsf9\appDevDebugProjectContainer(array(
    'container.build_hash' => '9hqxsf9',
    'container.build_id' => '7705212c',
    'container.build_time' => 1539266635,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9hqxsf9');
