user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

friend_delete:
    path:     /{id}/removeFriend
    defaults: { _controller: "AppBundle:User:removeFriend" }
    methods:  POST

friend_add:
    path:     /{id}/addFriend
    defaults: { _controller: "AppBundle:User:addFriend" }
    methods:  PATCH
